In [27]:
import pandas as pd
import numpy as np
from scipy.signal import convolve2d

In [189]:
input_alg="""..#.#..#####.#.#.#.###.##.....###.##.#..###.####..#####..#....#..#..##..##
#..######.###...####..#..#####..##..#.#####...##.#.#..#.##..#.#......#.###
.######.###.####...#.##.##..#..#..#####.....#.#....###..#.##......#.....#.
.#..#..##..#...##.######.####.####.#.#...#.......#..#.#.#...####.##.#.....
.#..#...##.#.##..#...##.#.##..###.#......#.#.......#.#.#.####.###.##...#..
...####.#..#..#.##.#....##..#.####....##...##..#...#......#.#.......#.....
..##..####..#...#.#.#...##..#.#..###..#####........#..####......#..#"""

input_image="""#..#.
#....
##..#
..#..
..###"""

In [199]:
input_alg = """##..##...#..#.#...#.....##....#.#..#.#.####...#####..#.######...#......#.##.#..######.########....#.#..##.####.##...##..#.########.#.##..........##.######.#......#..#...##..#..#.###.#.#..#..#...##.###.....#.#.###..##.####....##.#....#.#.###..###.....####..###..##.#.#..##....#.#....#####.##.....#.#.#..###..#.....####..##.#..#.###....#...##..###.#.###.##.####..#.##......##.##.#.##..##...##..######..####.#.##..###..###.###.##.##..###..#.......##.#######.#..##..##.###.#.#.#.####...####..#.#.#.......##.##.#....."""

input_image=""".#####..###.#.##.#..#.#.###..#......##.####.####.....##..#..#..#.#.##..##..##..#...##..#####....#.#.
..###..##..##.#.##.###..#.##..##.########..#...####.#..#.#.#...##.##.##.#....####...#......###.#.#..
###.###.###.#..#.#.#.##.#..#.######.##.#..##...#.#...##......#.###...###.#.#.#..##...######.###..#..
.######..##.#.##.####.....#..###.##..###....##..#.#.....#.##.....##.####.#...##..###...##...#.##.#.#
##...#.#.##.#.###...#.##.#..##.#.##.##.#####...#.##..#..###.#.##...##...#.###.###.#.#.##.##..#......
..##....#.##.#....#.####.#.#...####..##...#..#.##.##.#.###.#..##.#..##......#####.#.###..#.##..##..#
..##.....#..#.#####.....#..####...###.#..#.##.#....#.##.#...####.##.....##........#...###.#.#.##.#.#
##..##.........##.#..##..#.####.#.........#.##.#..####..####.....#....#.#..##.###...#..#.#...#.#..##
....###.###.#....##.#...#..####..##.###.###.#.####.##.##.#####..####.####.#...#.#.#.....#.##.##.###.
#...#.#.###...#...#.#..##..#.##.#.##.##...#.#.#..#.##..#.#.....####...##.#####....#.#..#...#...##.#.
#.#...###....##..##...###..#..#####.#.###...##......##..###.##.#.#...#...#.#...###..#.####..#.......
.###....##.##...###.###.#.#.#.##..#..#..###..#..#.#..#.#....##....#.#.#.#....#.#.#..#.#.#..##..#....
###..#..##.###.#.####..####........#.#.##..##..#...#...#...##.##.#.....#.#..#..#..#.#...##...###.###
..##.#......#...###...###########.###..#.#..###....###..##.###..#....#######.#..###.##..###......###
..###..#.#.#.#.....####.#.#..#..#.####..#..#.#.##.##########.##.#.#.#....########.##...#..#..#.#..##
###....###.#.#....###.##...#..##.#..##...####....####.####...##..##.....#####.#......###.##..#..#...
#.###.#.#..#...#..#..#...#...#......#..###.####...##.#.###.....###.###..#...#...####.##..#.###.#.#..
##.###.##..##..#..#...####......##.#.#.#.###.#....##..###.#.##.#....#####..##..........#.##.#..#.#.#
.#.#.#.#####..##...#####..#####..###.#######....#..#.####..#.#..##....##.#..#.....#..###.##.#...#.#.
.#...#..#.....##....#.#####.##...###..#####..#.#####.#.#..####...#..###...#.###..###....#..#.##.....
#..##.##...###.##.#.#....##.....#.#.####...##.#.#..###....##.#..#..#.####.#.#.##.##.#.####.##.###.#.
.#..#.###...#..###.....####..##.##.....##.....#......#######...#.###..#.##.##....##.##.####..#######
#..#.#####.#.#.#..#.#.##..##.###....#####.##.##..#####.#..###..#...#.##........####...##..###.#...##
#.##.#..#...########.....##.####.#...##.#.##...#..##.#.#..##.....###..##...#######....####..##.#....
####.....####.##.##.##.######...#.####.#.#.#.#..##.##.#..####.#.#..#.##...#.#...##########..#.##..##
.##.#######.###.####..#....##...###..#.#.#..##....#......#.#...#.#..###..###...##.#######.#.####..##
..#.#......#...#######.#..#...######.#.#.#.#...##.#....######.#..#####.##.......#.#####....#####...#
####.####.##..#..#..###..###....#...###..#..#..#.##.##..##.##..###.####.####.##..##...###..##..#.###
.##.#......###.####..###..#....#..##.#.#.#.##.#...#.##...##.....#.######..######.##.#...####..###...
##.####.#.#..##..#.########.....#.##..#..#....#.#.#..#..#.#...##..#.#...##...#####.#...####.#######.
##.#..#.###.....#.##....#.#.#...#####.#.#######..##.#..#####.####..#.#.##.#..#...##.##.######.##..##
##..#.##..###...###..###....###.#....#.##...#.#.###......####.###..#######.#.#........##...#.#.##..#
#..##.#..#..####....#.###...#.#...##.#..#.#.####.#..##.###.##.##..#.##..#.##.##.#..#.....##....#..#.
#######.#.#.###.#####.....#.#..###..####.#...#...###..####.#..#.#.#.#.#...##...#.####.#.#.....#.####
##.###...####..##.#..#.#.##.#....#.###.###.####..####..####....###.###.##..###.#.##..##.#..#######.#
...###...#....######....###..#..#..##..###...###..###.####.####....##.#..#.#.#.#..#####.##.#..##..#.
#.....########.####.#....#.#####.#.....###.#.##..##...####.#.#.#.##..##.##.#.##.#####..#..#.##.##.#.
#..#.#.#......#.#.####.#.###.#.#.##..##.##.#...#..#.##..#.##.#..##.#...####.#.####.##.#......##.#.#.
####.#..#.##.######....##.....#.######.....###...##.##.....##.#...##..........#.#.##.##..#.##..#####
...###..##..#.#..####.#...#..#..##.#..##.#..####...#..#..##.#...#.##...##...###..#.####.......#..##.
.#.###.....#.####..#..#.##....###.##..##.#####.#...###.##.##..##.####.#..###.#####.##....#.##..###..
.#..##....##..#.##.##..##.....#..##.#.#....#..##.#..#.###..#.......###.##.###....####...##.#####..##
.#.##.#.#....####..####.#......#.....#####.#.####...#.##.#...###.#.#..##.#.##.#.##..##.#######...#..
##..###.#..#.#..#...###.....#.#....##.##.#.##.##.#..######...#..#..#.......###.#.####...#.######...#
#...###..#......#..#...#....###.....##.##.##.##....#####.##....##.##.#....##..#...##..#.##..#.#.#..#
.....#.#.###.#.####..#....####.#####......##.##..####.#.#.#....#..#....######.#.###...###..###..#...
.#.#.#.#....#.#.....##..#...##.##.#..###.#.#.#.###......#.############.#............#..#..##.......#
#.##.#..####.##.##..##..#.####.#...##.##..#####.###..##..#.######.#.###....#.##..##..#....#..####...
#..###...###..#.##....#......##...###...##..#..#..#.#.#.#.##....#......##..##.#.#.####..##..#..#.##.
#.#.....##...#...#####...#.#####....#..###..#..#..####.##.#..##..#.###..#...#.#.#.##..##.#.....##.#.
..#.###..##.###..###.....#.###.#######.#.....#.#####.#...####.....#...#######..#.#.#.#..##.##.#.##..
####...#.#..#.##..#.##....#..####..#..####...##.#....###..#..#..#.#.###...#..#####...#.##.##.##..#..
.#.#..##.######..##.#.##...##...#.........#..#.###....#..#....####.##....#####..#....##.####..#.####
.#..##....#..##....#.###.######.#..#..#.###.####.#.#.#..####...###.##.##..#..#...#..#.###.##.###.###
......###.#..#..#..#.#.#.#...#.#..#...#....#.##..#.##.#.....##....####.#..##..##....#..#.#.##.#..##.
#..##.##..#######.#...##....#..###.#.##.###.##.###..#.###.#...#.#...##.#.###....###.#.##.#.#....#.##
#...####..######...####.#.##..###..#.#####.##...#.####.#.#....####.#..#.......###...##.#..#..##...##
##..#..##.#.###.#.#..#.#.###..#.......###..#.#.#.###........#...#.#..#.....##.####...#####.###....##
...#...#######.#..#########.#.#..#..###..#.#..#######.#.#....#.#.##.###.###.#######.####.....##.#.#.
..#...#####.#.##...##...#.#.##.#.###.#..###.#.#...##.#..#.#..###.#..#.#....#.###..###.#..##.....####
.#.###.#.#..#.####..#.###....##..#.#...##..#.###.#.#.##..#.#.#.....##.#...##.##..#.....#..##.#.###.#
#..#.###.##..#..###....#...#.#.###..#....####.##.##.#.#...#..#..####.##.##.##.###...####...####....#
.#.#...##.#.##.....#.#.##..#.#...#.#.#...##.....##.#...#####...##..##...#..##.##.##.#.##.##.....##.#
.######.###..#.#.######.###.#.#...#..#.#.#..#..##......####.##...#..#.#.#.###..####.##.######.######
.##.##...#......##.#....######.##.###.####...##...##.#.#.#.#.##...#######..#....##.#..#....###......
.#.##.###....#..#..#...###...#...#.#.....###.##.###.#........##.#.##.###..##.#####.##..##.##.#.#.#.#
..##..####.##.#..###.##.#..###.###.#####.####.#.##.####..#...#..#.###.#.#....#.##..##.#..##....##..#
.....#.#..##...#.#..##.#..#.#########..##.##.#...###..######...#.#.....#...###.##..##..#.#.......#.#
..#.#.#.#...###..####.###.##..#.##.###..#.#...##.....#.#..###.#..#.###..#.###..###.#.##...####.#....
#..#.###..#.#.##.#..##.###...##..............##.###.#.##...#.##..#...##........#.#.###.##....#.#.##.
##....####.##.#......###..#.....#.....#..####.....#..#.#.####...###...#...#.#...####..#..#..#..###..
.#....#..#####....#.#.#.#...#....##....##.#..###.#....#.#######.#.####.##...##..#....#......#.#.#.##
#.##....#####.#######...#.####.#..#..##..#.######..####..####..#..#...#.#.###.###....#..#....#.#####
###.#####...#.##.#.#####.#.#################.#..#..##.##...#.#...###..#.#.#.##.##..###.#..##.##..###
.#.##.##.###.#.##.#.###.##....#.....##..##...##.#########.##.##.#.###..##..#..#.#####..###.#...#..##
#.#....###..#.###..#...#..#.###.#.##..#..#.##...#...#..##..###..######....#.##.#..#.........##.#.##.
#.#.##.#.#####.#.#..#..###..#...###.###..##.##...##....#..##..##....#....#...##.#####..###..#..####.
#.#..##..##..##..##...####.#..#.####.##.#.##..#....###.#.####.####..#.###.###.#.#..#.#...#.#..#.....
#.#...####..#######.#.##..#.#......##.....######..#..##...##.#..#.#####.#..#..#....#.#..#####.#...##
.#.#.######.##....#..###.#...#.#....#.......#..#.#.#..#....##.#..###..##..#.#......####.#.#.##...##.
##..###..####...###.####...#.###....#.#######.##.####.#.....#.#.###.####.####...#.#.....#....##..###
..#.#.#.#.###...##.##..##..#.######..###..#...#......##.#.###....#.###...#.....#....####..###.##.#.#
.###..##..###.....##...#......####.##.#....###..#.##.#..#.##.##..#.....#.#.##..##.####..###.#...#..#
.#....####..##.#...###.#..#..###..##.#.#.....#...#.###..####..######.#.#...#...#.#...##.....###.....
.....#.#...#...#..#.###....##.##.#.#.#.#.##...##.#.#.....#.###.#.#.##.######.....#.###.###.#.##.###.
.####....#..###.#####.#.#..#.#.#..##.....##.#.#.#...#####..##.#.......###.###.#.##.#..##.#.###.#.#.#
##.#.#......#####..#.##.##..###..##..###.#..##..##.#.###.....#...####......#..###....#..##.#..#....#
#.#.#####...##.##.#...##.###..######.###.#.##.##..#..#...##..##.###...#.#..##.#########.#####.#.##.#
.#.##....#..#..#..#..##...#......#..#.#.##...##...#.###.##.......####...#.#..#.#...##.#..#.####..##.
.#.######.#.##...#####.###..#..##....##.#####.###..######.#...###.#.##..##....###..####.##.#.####.##
.#.#....#.##..##...#########...#..#.#.######.#.#.##.#....####.#...#.##..#..#.#.#..#.#.##..#.#...#.#.
.####...#...#..##.#.#.###.####...#.#...#####.....###.####.#.##..###..#.##.#...#.#####.####..##.##.#.
....#..#...#.###..##.##..#..####.#.#...#.#####..##...#####.#.#...###..#...#.#.###.#.#.##..###..###.#
#####.........##..###.#.###.#..........#.#.#..#.#..#.#.#######.#....##....#.###..#.#..##.#...##....#
.....###.##..#....#..#.#...#.##.#..#.#####.####.##.#.#.###........##..#.#..#.....###......##..##.#..
.###....#.#....#......##.##....##....#.#.##.######.#.##..##.###...#....#..#..#..###..##.#.#.##.#.#.#
##....#.##.#..#.###..##.##..#.#..###.##........##.#.#..#..####...####.#...#....#.#.##..#...#.####.#.
....###.##.#####.#....##.##.##.#..#.#..#.##.##.#.####.##..#.##.#...##..####..#..#.#.##.##...##.#....
..###........####.#....##.##..##..##.#....###..#.#.###......#.#####.###...##..##..#..#.#.###.#.#..#.
....#.###.##.....#..#.#.#.#####.###.#.##.#.##.......#.###.#.##..###........#.#.###.####.##.#....#.#."""

In [200]:
# conv = [2**i for i in range(8,-1,-1)]

conv = [2**i for i in range(0,9)]
conv = np.array(conv).reshape(3,3)
conv

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [201]:
input_alg = input_alg.replace('\n','')
input_alg = [False if y == '.' else True for y in input_alg]
# input_alg

In [202]:
arr_in = [[False if y == '.' else True for y in x] for x in input_image.split('\n')]
arr_in
arr = np.array(arr_in, dtype=bool)
arr


array([[False,  True,  True, ..., False,  True, False],
       [False, False,  True, ...,  True, False, False],
       [ True,  True,  True, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False,  True, False],
       [False, False, False, ..., False,  True, False]])

In [203]:
# arr[0,1]
arr.shape

(100, 100)

In [204]:
# part 1
lookup = lambda t: input_alg[t]
vfunc = np.vectorize(lookup)
vfunc(convolve2d((arr), conv))

array([[ True,  True, False, ..., False,  True,  True],
       [ True, False,  True, ..., False,  True,  True],
       [ True, False,  True, ..., False,  True,  True],
       ...,
       [ True,  True, False, ...,  True, False,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [205]:
vfunc(convolve2d((vfunc(convolve2d((arr), conv))), conv))

array([[ True, False, False, ..., False, False,  True],
       [ True, False,  True, ..., False, False, False],
       [ True,  True, False, ...,  True, False, False],
       ...,
       [ True,  True,  True, ..., False,  True, False],
       [False, False,  True, ..., False,  True,  True],
       [ True, False,  True, ...,  True,  True,  True]])

In [206]:
out = vfunc(convolve2d((vfunc(convolve2d((arr), conv))), conv,fillvalue=input_alg[0]))
out

array([[False, False, False, ..., False, False, False],
       [False, False,  True, ...,  True, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [213]:
sum(sum(out))

19114

In [237]:
#part #2
times = 50
times -= 1
fill_value = False
out = vfunc(convolve2d(arr,conv,fillvalue=fill_value))
while times >0:
    times -= 1
    if input_alg[0]:
        fill_value = not fill_value
    out = vfunc(convolve2d(out,conv,fillvalue=fill_value))

sum(sum(out))

15287